# Generated by Django 3.2.7 on 2021-09-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures/'),
        ),
    ]
